project_id = "fziszuqxogariodpbbcx"

[functions.validate-csd]
verify_jwt = true

[functions.facturama-create-cfdi]
verify_jwt = true

[functions.facturama-cancel-cfdi]
verify_jwt = true

[functions.facturama-reconcile-cfdi]
verify_jwt = true

[functions.send-invoice-email]
verify_jwt = true

[functions.create-checkout-session]
verify_jwt = true

[functions.cancel-subscription]
verify_jwt = false

[functions.daily-notifications-check]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
