/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedHistoryRouteImport } from './routes/_authenticated/history'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile.index'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products.index'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients.index'
import { Route as AuthenticatedProfileInvoicingRouteImport } from './routes/_authenticated/profile.invoicing'
import { Route as AuthenticatedProfileFiscalRouteImport } from './routes/_authenticated/profile.fiscal'
import { Route as AuthenticatedProfileCsdRouteImport } from './routes/_authenticated/profile.csd'
import { Route as AuthenticatedProductsNewRouteImport } from './routes/_authenticated/products.new'
import { Route as AuthenticatedProductsIdRouteImport } from './routes/_authenticated/products.$id'
import { Route as AuthenticatedInvoicesNewRouteImport } from './routes/_authenticated/invoices.new'
import { Route as AuthenticatedInvoicesIdRouteImport } from './routes/_authenticated/invoices.$id'
import { Route as AuthenticatedClientsNewRouteImport } from './routes/_authenticated/clients.new'
import { Route as AuthenticatedProductsIdEditRouteImport } from './routes/_authenticated/products.$id_.edit'
import { Route as AuthenticatedClientsIdEditRouteImport } from './routes/_authenticated/clients.$id.edit'

const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHistoryRoute = AuthenticatedHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileInvoicingRoute =
  AuthenticatedProfileInvoicingRouteImport.update({
    id: '/profile/invoicing',
    path: '/profile/invoicing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileFiscalRoute =
  AuthenticatedProfileFiscalRouteImport.update({
    id: '/profile/fiscal',
    path: '/profile/fiscal',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileCsdRoute = AuthenticatedProfileCsdRouteImport.update({
  id: '/profile/csd',
  path: '/profile/csd',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsNewRoute =
  AuthenticatedProductsNewRouteImport.update({
    id: '/products/new',
    path: '/products/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProductsIdRoute = AuthenticatedProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoicesNewRoute =
  AuthenticatedInvoicesNewRouteImport.update({
    id: '/invoices/new',
    path: '/invoices/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvoicesIdRoute = AuthenticatedInvoicesIdRouteImport.update({
  id: '/invoices/$id',
  path: '/invoices/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsNewRoute = AuthenticatedClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsIdEditRoute =
  AuthenticatedProductsIdEditRouteImport.update({
    id: '/products/$id_/edit',
    path: '/products/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsIdEditRoute =
  AuthenticatedClientsIdEditRouteImport.update({
    id: '/clients/$id/edit',
    path: '/clients/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/privacidad': typeof PrivacidadRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terminos': typeof TerminosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/invoices/$id': typeof AuthenticatedInvoicesIdRoute
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/products/$id': typeof AuthenticatedProductsIdRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/profile/csd': typeof AuthenticatedProfileCsdRoute
  '/profile/fiscal': typeof AuthenticatedProfileFiscalRoute
  '/profile/invoicing': typeof AuthenticatedProfileInvoicingRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/products/': typeof AuthenticatedProductsIndexRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
  '/clients/$id/edit': typeof AuthenticatedClientsIdEditRoute
  '/products/$id/edit': typeof AuthenticatedProductsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/privacidad': typeof PrivacidadRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terminos': typeof TerminosRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/history': typeof AuthenticatedHistoryRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/invoices/$id': typeof AuthenticatedInvoicesIdRoute
  '/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/products/$id': typeof AuthenticatedProductsIdRoute
  '/products/new': typeof AuthenticatedProductsNewRoute
  '/profile/csd': typeof AuthenticatedProfileCsdRoute
  '/profile/fiscal': typeof AuthenticatedProfileFiscalRoute
  '/profile/invoicing': typeof AuthenticatedProfileInvoicingRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
  '/clients/$id/edit': typeof AuthenticatedClientsIdEditRoute
  '/products/$id/edit': typeof AuthenticatedProductsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/privacidad': typeof PrivacidadRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terminos': typeof TerminosRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/history': typeof AuthenticatedHistoryRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/clients/new': typeof AuthenticatedClientsNewRoute
  '/_authenticated/invoices/$id': typeof AuthenticatedInvoicesIdRoute
  '/_authenticated/invoices/new': typeof AuthenticatedInvoicesNewRoute
  '/_authenticated/products/$id': typeof AuthenticatedProductsIdRoute
  '/_authenticated/products/new': typeof AuthenticatedProductsNewRoute
  '/_authenticated/profile/csd': typeof AuthenticatedProfileCsdRoute
  '/_authenticated/profile/fiscal': typeof AuthenticatedProfileFiscalRoute
  '/_authenticated/profile/invoicing': typeof AuthenticatedProfileInvoicingRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
  '/_authenticated/clients/$id/edit': typeof AuthenticatedClientsIdEditRoute
  '/_authenticated/products/$id_/edit': typeof AuthenticatedProductsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/privacidad'
    | '/reset-password'
    | '/terminos'
    | '/dashboard'
    | '/history'
    | '/settings'
    | '/clients/new'
    | '/invoices/$id'
    | '/invoices/new'
    | '/products/$id'
    | '/products/new'
    | '/profile/csd'
    | '/profile/fiscal'
    | '/profile/invoicing'
    | '/clients/'
    | '/products/'
    | '/profile/'
    | '/clients/$id/edit'
    | '/products/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/privacidad'
    | '/reset-password'
    | '/terminos'
    | '/dashboard'
    | '/history'
    | '/settings'
    | '/clients/new'
    | '/invoices/$id'
    | '/invoices/new'
    | '/products/$id'
    | '/products/new'
    | '/profile/csd'
    | '/profile/fiscal'
    | '/profile/invoicing'
    | '/clients'
    | '/products'
    | '/profile'
    | '/clients/$id/edit'
    | '/products/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/privacidad'
    | '/reset-password'
    | '/terminos'
    | '/_authenticated/dashboard'
    | '/_authenticated/history'
    | '/_authenticated/settings'
    | '/_authenticated/clients/new'
    | '/_authenticated/invoices/$id'
    | '/_authenticated/invoices/new'
    | '/_authenticated/products/$id'
    | '/_authenticated/products/new'
    | '/_authenticated/profile/csd'
    | '/_authenticated/profile/fiscal'
    | '/_authenticated/profile/invoicing'
    | '/_authenticated/clients/'
    | '/_authenticated/products/'
    | '/_authenticated/profile/'
    | '/_authenticated/clients/$id/edit'
    | '/_authenticated/products/$id_/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  PrivacidadRoute: typeof PrivacidadRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TerminosRoute: typeof TerminosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/history': {
      id: '/_authenticated/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof AuthenticatedHistoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/invoicing': {
      id: '/_authenticated/profile/invoicing'
      path: '/profile/invoicing'
      fullPath: '/profile/invoicing'
      preLoaderRoute: typeof AuthenticatedProfileInvoicingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/fiscal': {
      id: '/_authenticated/profile/fiscal'
      path: '/profile/fiscal'
      fullPath: '/profile/fiscal'
      preLoaderRoute: typeof AuthenticatedProfileFiscalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile/csd': {
      id: '/_authenticated/profile/csd'
      path: '/profile/csd'
      fullPath: '/profile/csd'
      preLoaderRoute: typeof AuthenticatedProfileCsdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/new': {
      id: '/_authenticated/products/new'
      path: '/products/new'
      fullPath: '/products/new'
      preLoaderRoute: typeof AuthenticatedProductsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/$id': {
      id: '/_authenticated/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof AuthenticatedProductsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/new': {
      id: '/_authenticated/invoices/new'
      path: '/invoices/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof AuthenticatedInvoicesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices/$id': {
      id: '/_authenticated/invoices/$id'
      path: '/invoices/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof AuthenticatedInvoicesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/new': {
      id: '/_authenticated/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof AuthenticatedClientsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products/$id_/edit': {
      id: '/_authenticated/products/$id_/edit'
      path: '/products/$id/edit'
      fullPath: '/products/$id/edit'
      preLoaderRoute: typeof AuthenticatedProductsIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/$id/edit': {
      id: '/_authenticated/clients/$id/edit'
      path: '/clients/$id/edit'
      fullPath: '/clients/$id/edit'
      preLoaderRoute: typeof AuthenticatedClientsIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHistoryRoute: typeof AuthenticatedHistoryRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedClientsNewRoute: typeof AuthenticatedClientsNewRoute
  AuthenticatedInvoicesIdRoute: typeof AuthenticatedInvoicesIdRoute
  AuthenticatedInvoicesNewRoute: typeof AuthenticatedInvoicesNewRoute
  AuthenticatedProductsIdRoute: typeof AuthenticatedProductsIdRoute
  AuthenticatedProductsNewRoute: typeof AuthenticatedProductsNewRoute
  AuthenticatedProfileCsdRoute: typeof AuthenticatedProfileCsdRoute
  AuthenticatedProfileFiscalRoute: typeof AuthenticatedProfileFiscalRoute
  AuthenticatedProfileInvoicingRoute: typeof AuthenticatedProfileInvoicingRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
  AuthenticatedClientsIdEditRoute: typeof AuthenticatedClientsIdEditRoute
  AuthenticatedProductsIdEditRoute: typeof AuthenticatedProductsIdEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHistoryRoute: AuthenticatedHistoryRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedClientsNewRoute: AuthenticatedClientsNewRoute,
  AuthenticatedInvoicesIdRoute: AuthenticatedInvoicesIdRoute,
  AuthenticatedInvoicesNewRoute: AuthenticatedInvoicesNewRoute,
  AuthenticatedProductsIdRoute: AuthenticatedProductsIdRoute,
  AuthenticatedProductsNewRoute: AuthenticatedProductsNewRoute,
  AuthenticatedProfileCsdRoute: AuthenticatedProfileCsdRoute,
  AuthenticatedProfileFiscalRoute: AuthenticatedProfileFiscalRoute,
  AuthenticatedProfileInvoicingRoute: AuthenticatedProfileInvoicingRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
  AuthenticatedClientsIdEditRoute: AuthenticatedClientsIdEditRoute,
  AuthenticatedProductsIdEditRoute: AuthenticatedProductsIdEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  PrivacidadRoute: PrivacidadRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TerminosRoute: TerminosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
